-   id: forbid-unencrypted-sops
    name: Forbid unencrypted SOPS files
    description: "Checks that files are encrypted with SOPS, i.e. have a top-level 'sops' key."
    entry: scripts/check-sops-encrypted.sh
    language: script