name: 'Check for unencrypted SOPS files'
description: 'Scans a repository for SOPS files that have not been encrypted.'
author: 'Blueshoe GmbH'

inputs:
  files-pattern:
    description: 'A glob pattern of files to check. Use quotes for the pattern.'
    required: false
    default: '"**/*.sops.yaml"'

runs:
  using: 'composite'
  steps:
    - name: Find and check files
      shell: bash
      run: |
        # Find files matching the pattern and pass them to the script
        find . -type f -wholename ${{ inputs.files-pattern }} -print0 | xargs -0 ${{ github.action_path }}/scripts/check-sops-encrypted.sh
